export const AppStrings = {
    hereWeLearn: 'Here we learn\nThirukural',
    hereWe2: 'lorem ipsum jhro eioru iuri u',
    skip: "Skip",
    tryWidgetsText1: 'From the Home Screen, touch and hold an empty area until the apps jiggle. ',
    tryWidgetsText2: 'Tap the "Plus" button in the upper-left corner. Select one of widgets. Now you can choose widget size, and add the widget.',
    swipeUp: 'Swipe up to continue',
    swipeUpFavs: 'Swipe up to view all favs',
    actions: 'Actions',
    modes: 'Switch Modes',
    appTheme: 'App Theme',
    favs: 'Favorites',
    kuralNum: 'Number',
    chapter: 'Chapter',
    iyal: 'Iyal',
    pall: 'Pall',
    explain: 'Explanation',
    translate: 'Translation',
    kuralNumTam: '',
    athigaram: '',
    iyalTamil: '',
    pallTamil: '',
    vilakam: '',
    themes: 'Themes',
    chooseTheme: 'Choose a theme that you \n are interested in',
    noData: 'No Data Available !!',
}